# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

env:
  PACKAGE_WITH_VERSION: gtfu-1.4.0

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: ls and pip list
        run: |
          ls -AGhl
          python -m pip list

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install build

      - name: ls and pip list
        run: |
          ls -AGhl
          python -m pip list

      - name: Build package
        run: python -m build

      - name: ls and ls ./dist and pip list
        run: |
          ls -AGhl
          ls -AGhl ./dist
          python -m pip list

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@f5622bde02b04381239da3573277701ceca8f6a0
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

      - name: List ./dist files
        run: |
          ls -AGhl
          ls -AGhl ./dist
          tar zxvf dist/${{ env.PACKAGE_WITH_VERSION }}.tar.gz -C ./dist
          unzip dist/${PACKAGE_WITH_VERSION}-py3-none-any.whl -d ./dist
          ls -AGhl ./dist
          ls -AGhl ./dist/${{ env.PACKAGE_WITH_VERSION }}
          ls -AGhl ./dist/${{ env.PACKAGE_WITH_VERSION }}.dist-info
          ls -AGhl
          python -m pip list
          pip list

      - run: ls ${{ github.workspace }}
